Fix compile problem with ConstantConfigManager
The ConstantConfigManager doesn't have a clearApplyPending() method causing
the compiler to complain:
./aprinter/printer/PrinterMain.h:2220:44: error: 'clearApplyPending' is not a member of 'APrinter::PrinterMain<MyPrinter_arg>::TheConfigManager {aka APrinter::ConstantConfigManager<APrinter::PrinterMain<MyPrinter_arg>::TheConfigManager_arg>}'
         TheConfigManager::clearApplyPending(c);